---
Metrics/AbcSize:
  Enabled: false
Metrics/CyclomaticComplexity:
  Enabled: false
Metrics/PerceivedComplexity:
  Enabled: false
Metrics/LineLength:
  Max: 255
Metrics/BlockLength:
  Max: 144
Metrics/MethodLength:
  Max: 32
Style/GuardClause:
  Enabled: false
Style/HashSyntax:
  Enabled: false
Style/FormatString:
  Enabled: false
Style/FormatStringToken:
  Enabled: false
Style/SpecialGlobalVars:
  Enabled: false
Style/StringLiterals:
  Enabled: false
